config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  "pages#home"
  get   "pages/about" => "pages#about"

  # Article Routes
  resources :articles

  # User Routes
  get 'signup' => 'users#new'
  resources :users, except: [:new]

  # Session Routes
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # Categories Routes
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
                       length: { minimum: 5, maximum: 25 }, 
                       uniqueness: { case_sensitive: false }

  # Check it out at rubular.com
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                    length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    # return @current_user if any, otherwise check to db and store
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created!"
      redirect_to article_path(@article)
    else
      # This will render the new again in case the action fails
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated!"
      redirect_to article_path(@article)
    else
      # This will render the new again in case the action fails
      render 'new'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account" 
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %> 
  <div class="card" style="margin-bottom: 4px;">
    <div class="card-header">
      <div class="card-body">
        <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
        <p class="card-text"><%= truncate(article.description, length: 150) %></p>
        <small class="badge badge-dark">Created by: <%= article.user.username if article.user %></small> <small class="badge badge-secondary"><%= time_ago_in_words(article.created_at) %> ago</small> <small class="badge badge-light">last updated: <% time_ago_in_words(article.updated_at) %> ago</small>
        <% if article.categories.any? %>
          <hr>
          <p>Categories: <%= render article.categories %>
        <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article? "}, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %> 

app/views/articles/_form.html.erb
<!-- Later you can re-use the _errors.html.erb using the way below -->
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group row">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
        </div>
      </div>

      <div class="form-group row">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of Article", autofocus: true %>
        </div>
      </div>

      <div class="form-group row">
        <div class="control-label col-sm-2"></div>
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do | cb| %>
          <% cb.label(class: "form-check form-check-inline") {cb.check_box(class: "form-check-input") + cb.text} %> 
        <% end %>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %><br/>
        </div>
      </div>
    <% end %>
      
    <div class="col-xs-4 col-xs-offset-4" align="center">
      [ <%= link_to "Cancel Request & Return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <ul class="listing">
    <div class="row center">
      <div class="col-md-4 offset-md-4">
        <li>Created by: </li>
        <li>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        </li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li>
          <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
        </li>
      </div>
    </div>
  </ul>
  <h5 class="center"><strong>Description:</strong></h5>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %>
  <% end %>
  <hr>
  <%= simple_format(@article.description) %>
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <div class="article-actions">
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article? "}, class: "btn btn-xs btn-danger" %>
      <% end %>
      <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-light"><%= link_to category.name, category_path(category) %> &nbsp;

app/views/categories/_form.html.erb
<!-- Later you can re-use the _errors.html.erb using the way below -->
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group row">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Enter Category Name", autofocus: true %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %><br/>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 align="center">Edit existing category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>

<% @categories.each do |category| %>
  <div class="card" style="margin-bottom: 5px;">
    <div class="card-body">
      <%= link_to "#{category.name}", category_path(category) %> 
      <br>
      <small><%= pluralize(category.articles.count, "article") %></small>
    </div>
  </div>
<% end %>

<%= will_paginate %>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>
  
<div class="col-xs-4 col-xs-offset-4" align="center">
  [ <%= link_to "Cancel Request & Return to articles listing", articles_path %> ]
</div>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>

<% if logged_in? and current_user.admin? %>
  <div class="row">
    <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
  </div>
<% end %>

<%= render 'articles/article', obj: @category_articles %>

<div align="center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer has-cards">
  <div class="container">
    <div class="row row-grid align-items-center my-md">
      <div class="col-lg-6">
        <h3 class="text-primary font-weight-light mb-2">Thank you for visiting!</h3>
        <h4 class="mb-0 font-weight-light">Let's get in touch on any of these platforms.</h4>
      </div>
      <div class="col-lg-6 text-lg-center btn-wrapper">
        <a target="_blank" href="https://twitter.com/creativetim" class="btn btn-neutral btn-icon-only btn-twitter btn-round btn-lg" data-toggle="tooltip" data-original-title="Follow us">
          <i class="fa fa-twitter"></i>
        </a>
        <a target="_blank" href="https://www.facebook.com/creativetim" class="btn btn-neutral btn-icon-only btn-facebook btn-round btn-lg" data-toggle="tooltip" data-original-title="Like us">
          <i class="fa fa-facebook-square"></i>
        </a>
        <a target="_blank" href="https://dribbble.com/creativetim" class="btn btn-neutral btn-icon-only btn-dribbble btn-lg btn-round" data-toggle="tooltip" data-original-title="Follow us">
          <i class="fa fa-dribbble"></i>
        </a>
        <a target="_blank" href="https://github.com/creativetimofficial" class="btn btn-neutral btn-icon-only btn-github btn-round btn-lg" data-toggle="tooltip" data-original-title="Star on Github">
          <i class="fa fa-github"></i>
        </a>
      </div>
    </div>
    <hr>
    <div class="row align-items-center justify-content-md-between">
      <div class="col-md-6">
        <div class="copyright">
          &copy; 2018
          <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.
        </div>
      </div>
      <div class="col-md-6">
        <ul class="nav nav-footer justify-content-end">
          <li class="nav-item">
            <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
          </li>
          <li class="nav-item">
            <a href="https://github.com/creativetimofficial/argon-design-system/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= "#{name}"%> alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="header-global">
  <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light headroom">
    <div class="container">
      <a class="navbar-brand mr-lg-5" href="./index.html">
        <img src="img/brand/white.png">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbar_global">
        <div class="navbar-collapse-header">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="./index.html">
                <img src="./assets/img/brand/blue.png">
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
          <li class="nav-item dropdown">
            <a href="<%= articles_path %>" class="nav-link" data-toggle="dropdown" href="#" role="button">
              <i class="ni ni-ui-04 d-lg-none"></i>
              <span class="nav-link-inner--text">Hover Me!</span>
            </a>
            <div class="dropdown-menu dropdown-menu-xl">
              <div class="dropdown-menu-inner">
                <a href="<%= pages_about_path %>" class="media d-flex align-items-center">
                  <div class="icon icon-shape bg-gradient-success rounded-circle text-white">
                    <i class="ni ni-palette"></i>
                  </div>
                  <div class="media-body ml-3">
                    <h6 class="heading text-primary mb-md-1">About</h6>
                    <p class="description d-none d-md-inline-block mb-0">Check details about the author</p>
                  </div>
                </a>
                <a href="<%= articles_path %>" class="media d-flex align-items-center">
                  <div class="icon icon-shape bg-gradient-primary rounded-circle text-white">
                    <i class="ni ni-spaceship"></i>
                  </div>
                  <div class="media-body ml-3">
                    <h6 class="heading text-primary mb-md-1">Articles</h6>
                    <p class="description d-none d-md-inline-block mb-0">Read articles will enhance your knowledge</p>
                  </div>
                </a>
                <a href="<%= users_path %>" class="media d-flex align-items-center">
                  <div class="icon icon-shape bg-gradient-warning rounded-circle text-white">
                    <i class="ni ni-ui-04"></i>
                  </div>
                  <div class="media-body ml-3">
                    <h5 class="heading text-warning mb-md-1">Users</h5>
                    <p class="description d-none d-md-inline-block mb-0">Knowing who made the articles</p>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link" data-toggle="dropdown" href="#" role="button">
                <i class="ni ni-collection d-lg-none"></i>
                <span class="nav-link-inner--text">Actions</span>
              </a>
              <div class="dropdown-menu">
                <a href="<%= new_article_path %>" class="dropdown-item">New Article</a>
                <a href="<%= categories_path %>" class="dropdown-item">Categories</a>
                <a href="./examples/login.html" class="dropdown-item">Login</a>
                <a href="./examples/register.html" class="dropdown-item">Register</a>
              </div>
            </li>
          <% end %>

          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link" data-toggle="dropdown" href="#" role="button">
                <i class="ni ni-collection d-lg-none"></i>
                <span class="nav-link-inner--text">Categories</span>
              </a>
              <div class="dropdown-menu">
                <a href="<%= categories_path %>" class="dropdown-item">All Categories</a>

                <% Category.all.each do |category| %>
                  <%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %>
                <% end %>

                <% if logged_in? and current_user.admin? %>
                  <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <% if logged_in? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Your Profile <%= "| Admin" if current_user.admin? %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                </div>
              </li>

              <li class="nav-item">
                <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", login_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign Up", signup_path, class: "nav-link" %>
              </li>
            <% end %>  
          </li>
        </ul>
        <ul class="navbar-nav align-items-lg-center ml-lg-auto">
          <li class="nav-item">
            <a class="nav-link nav-link-icon" href="https://www.facebook.com/creativetim" target="_blank" data-toggle="tooltip" title="Like us on Facebook">
              <i class="fa fa-facebook-square"></i>
              <span class="nav-link-inner--text d-lg-none">Facebook</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-link-icon" href="https://www.instagram.com/creativetimofficial" target="_blank" data-toggle="tooltip" title="Follow us on Instagram">
              <i class="fa fa-instagram"></i>
              <span class="nav-link-inner--text d-lg-none">Instagram</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-link-icon" href="https://twitter.com/creativetim" target="_blank" data-toggle="tooltip" title="Follow us on Twitter">
              <i class="fa fa-twitter-square"></i>
              <span class="nav-link-inner--text d-lg-none">Twitter</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-link-icon" href="https://github.com/creativetimofficial/argon-design-system" target="_blank" data-toggle="tooltip" title="Star us on Github">
              <i class="fa fa-github"></i>
              <span class="nav-link-inner--text d-lg-none">Github</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rizkiadi23's | Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
     <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
 
    <!-- Icons -->
    <link href="vendor/nucleo/css/nucleo.css" rel="stylesheet">
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <!-- Argon CSS -->
    <%= stylesheet_link_tag '/css/argon.min.css' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>

    <div class="container" style="background-color: #f8f9fa;">
      <hr>
      <%= debug(params) if Rails.env.development? %>
      <hr>
    </div>
    <%= render 'layouts/footer' %>

    <script src='vendor/jquery/jquery.min.js'></script>
    <script src='vendor/popper/popper.min.js'></script>
    <script src='vendor/bootstrap/bootstrap.min.js'></script>
    <script src='vendor/headroom/headroom.min.js'></script>
    <script src='vendor/onscreen/onscreen.min.js'></script>
    <script src='vendor/nouislider/js/nouislider.min.js'></script>
    <script src='vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js'></script>
    <script src='js/argon.min.js'></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is About Page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-12 alert alert-warning" role="alert">
      <h2 class="panel-title"><%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:</h2>

      <% obj.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<!-- Later you can re-use the _errors.html.erb using the way below -->
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group row">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true %>
        </div>
      </div>

      <div class="form-group row">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter Email", autofocus: true %>
        </div>
      </div>

      <div class="form-group row">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter Password", autofocus: true %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary btn-lg") %><br/>
        </div>
      </div>
    <% end %>
      
    <div class="col-xs-4 col-xs-offset-4" align="center">
      [ <%= link_to "Cancel Request & Return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="card" style="margin-bottom: 5px;">
      <div class="card-body">
        <%= link_to user.username, user_path(user) %>'s has <%= pluralize(user.articles.count, "article") if user.articles %> 
        <% if logged_in? and current_user.admin? %>
          | <%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure want to delete the user and all their articles?" } %>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup User for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
  <div class="col-md-12">
    <center><%= gravatar_for @user, size: 150 %></center>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s articles</h4>

<%= render 'articles/article', obj: @user_articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>